import fs from 'node:fs';
import assert from 'node:assert/strict';
import {Connection,Keypair,PublicKey,SystemProgram,Transaction,TransactionInstruction,sendAndConfirmTransaction,LAMPORTS_PER_SOL} from '@solana/web3.js';
const RPC='https://api.devnet.solana.com',PROGRAM=new PublicKey('6PFsiUA7sX5j96pzK7zxLbpFpsJXNLkfwQPYyd4UNFTy'),TREASURY=new PublicKey('4F66AtVCpftxwQ8SbcFdXkyCcubvfMhUpHddJ4AtN5HY'),CONFIG=new PublicKey('DXvdV1M6xe7xmt2n5RC8YbqCmsGZrvvnxs8WoVxQmh29');
const payer=Keypair.fromSecretKey(Uint8Array.from(JSON.parse(fs.readFileSync(process.env.DEPLOYER_KEYPAIR,'utf8')))),connection=new Connection(RPC,'confirmed');
const u64=n=>{const b=Buffer.alloc(8);b.writeBigUInt64LE(BigInt(n));return b},i64=n=>{const b=Buffer.alloc(8);b.writeBigInt64LE(BigInt(n));return b};const send=(ixs,signers)=>sendAndConfirmTransaction(connection,new Transaction().add(...ixs),[payer,...signers],{commitment:'confirmed'});
async function fund(keypair,sol=.03){await send([SystemProgram.transfer({fromPubkey:payer.publicKey,toPubkey:keypair.publicKey,lamports:sol*LAMPORTS_PER_SOL})],[])}
function derive(creator,seed){const[commission]=PublicKey.findProgramAddressSync([Buffer.from('commission'),creator.toBuffer(),u64(seed)],PROGRAM),[vault]=PublicKey.findProgramAddressSync([Buffer.from('vault'),commission.toBuffer()],PROGRAM);return{commission,vault}}
function create(creator,seed,goal,bps){const{commission,vault}=derive(creator,seed),count=Buffer.alloc(4);count.writeUInt32LE(bps.length);return{commission,vault,ix:new TransactionInstruction({programId:PROGRAM,keys:[{pubkey:creator,isSigner:true,isWritable:true},{pubkey:CONFIG,isSigner:false,isWritable:false},{pubkey:commission,isSigner:false,isWritable:true},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false}],data:Buffer.concat([Buffer.from([1]),u64(seed),u64(goal),count,...bps.map(x=>{const b=Buffer.alloc(2);b.writeUInt16LE(x);return b}),i64(Math.floor(Date.now()/1000)+86400),i64(0),i64(0)])})}}
function pledge(backer,commission,vault,amount){const[pledgePda]=PublicKey.findProgramAddressSync([Buffer.from('pledge'),commission.toBuffer(),backer.toBuffer()],PROGRAM);return{pledgePda,ix:new TransactionInstruction({programId:PROGRAM,keys:[{pubkey:backer,isSigner:true,isWritable:true},{pubkey:CONFIG,isSigner:false,isWritable:false},{pubkey:commission,isSigner:false,isWritable:true},{pubkey:pledgePda,isSigner:false,isWritable:true},{pubkey:vault,isSigner:false,isWritable:true},{pubkey:SystemProgram.programId,isSigner:false,isWritable:false}],data:Buffer.concat([Buffer.from([2]),u64(amount)])})}}
const creator=Keypair.generate(),backer=Keypair.generate(),agent=Keypair.generate();await fund(creator);await fund(backer,.05);await fund(agent);const seed=Date.now(),flow=create(creator.publicKey,seed,10_000_000,[5000,5000]);const createSig=await send([flow.ix],[creator]);const p=pledge(backer.publicKey,flow.commission,flow.vault,10_000_000),beforeVault=await connection.getBalance(flow.vault);const pledgeSig=await send([p.ix],[backer]);assert.equal((await connection.getBalance(flow.vault))-beforeVault,10_000_000);const nominateSig=await send([new TransactionInstruction({programId:PROGRAM,keys:[{pubkey:creator.publicKey,isSigner:true,isWritable:false},{pubkey:flow.commission,isSigner:false,isWritable:true},{pubkey:agent.publicKey,isSigner:false,isWritable:false}],data:Buffer.from([3])})],[creator]);const acceptSig=await send([new TransactionInstruction({programId:PROGRAM,keys:[{pubkey:agent.publicKey,isSigner:true,isWritable:false},{pubkey:flow.commission,isSigner:false,isWritable:true}],data:Buffer.from([8])})],[agent]);const agentBefore=await connection.getBalance(agent.publicKey),treasuryBefore=await connection.getBalance(TREASURY);const releaseSig=await send([new TransactionInstruction({programId:PROGRAM,keys:[{pubkey:creator.publicKey,isSigner:true,isWritable:false},{pubkey:flow.commission,isSigner:false,isWritable:true},{pubkey:flow.vault,isSigner:false,isWritable:true},{pubkey:agent.publicKey,isSigner:false,isWritable:true},{pubkey:TREASURY,isSigner:false,isWritable:true}],data:Buffer.from([4,0])})],[creator]);const releaseTx=await connection.getTransaction(releaseSig,{commitment:'confirmed',maxSupportedTransactionVersion:0});assert.equal((await connection.getBalance(agent.publicKey))-agentBefore,4_950_000);assert.equal((await connection.getBalance(TREASURY))-treasuryBefore+releaseTx.meta.fee,50_000);
const cancelled=create(creator.publicKey,seed+1,20_000_000,[10000]);const create2Sig=await send([cancelled.ix],[creator]);const p2=pledge(backer.publicKey,cancelled.commission,cancelled.vault,5_000_000),pledge2Sig=await send([p2.ix],[backer]);const cancelSig=await send([new TransactionInstruction({programId:PROGRAM,keys:[{pubkey:creator.publicKey,isSigner:true,isWritable:false},{pubkey:cancelled.commission,isSigner:false,isWritable:true}],data:Buffer.from([6])})],[creator]);const treasuryBeforeRefund=await connection.getBalance(TREASURY),refundSig=await send([new TransactionInstruction({programId:PROGRAM,keys:[{pubkey:backer.publicKey,isSigner:true,isWritable:true},{pubkey:cancelled.commission,isSigner:false,isWritable:true},{pubkey:p2.pledgePda,isSigner:false,isWritable:true},{pubkey:cancelled.vault,isSigner:false,isWritable:true},{pubkey:TREASURY,isSigner:false,isWritable:true}],data:Buffer.from([5])})],[backer]);const refundTx=await connection.getTransaction(refundSig,{commitment:'confirmed',maxSupportedTransactionVersion:0});assert.equal((await connection.getBalance(TREASURY))+refundTx.meta.fee,treasuryBeforeRefund);console.log(JSON.stringify({ok:true,program:PROGRAM.toBase58(),release:{createSig,pledgeSig,nominateSig,acceptSig,releaseSig},refund:{create2Sig,pledge2Sig,cancelSig,refundSig},assertions:['pledge fee 0','release fee 1%','refund fee 0']},null,2));connection._rpcWebSocket?.close();